from .base import DOCSTRING_FOR_CLASS_DEFAULT, DOCSTRING_FOR_FUNCTION_DEFAULT, DOCSTRING_FOR_FUNCTION_CUSTOM
from .extended import DOCSTRING_FOR_CLASS, DOCSTRING_FOR_FUNCTION

__all__ = [
    "DOCSTRING_FOR_CLASS",
    "DOCSTRING_FOR_FUNCTION",
    "DOCSTRING_FOR_FUNCTION_CUSTOM",
    "DOCSTRING_FOR_CLASS_DEFAULT",
    "DOCSTRING_FOR_FUNCTION_DEFAULT",
]
