from .base import DOCSTRING_FOR_CLASS, DOCSTRING_FOR_FUNCTION
from .extended import DOCSTRING_FOR_CLASS_FULL, DOCSTRING_FOR_FUNCTION_FULL

__all__ = [
    "DOCSTRING_FOR_CLASS_FULL",
    "DOCSTRING_FOR_FUNCTION_FULL",
    "DOCSTRING_FOR_CLASS",
    "DOCSTRING_FOR_FUNCTION",
]
